# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c7acaa7e7ee49510c1e2661fc35101b3ebc8510c00c3bc7cb557aa7699b3e1612a1c0f0ddbeb6753b8ce63abdb0874c06560834d245d890bec0cd27877ecf4

test:
  secret_key_base: a331c39c86d777f38679c1cd868985abc3ea81535fc03771d12a99414c8c6bed786d0114b2deaa704912765cf037e3ec231cd7aeb92043bbc771379ccb962db3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
